name: Deploy pages
on: push
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install dependencies
        run: |
          cd presentation
          npm install
      - name: Install slidev
        run:  npm i -g @slidev/cli
      - name: Build
        run: |
          cd presentation
          slidev build --base typescript-who-even-need-template-literal-types-presentation
      - name: Deploy pages
        uses: crazy-max/ghaction-github-pages@v2
        with:
          build_dir: presentation/dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}